### ISSUE TITLE
Error on node index.js

### ISSUE THREAD

**Issue by marianvlad** [owenconti/livecodingtv-bot#2]
I have the latest version of node.js and I get this error when I want to start the bot. I've added credentials.js file.

Sun Oct 25 2015 15:59:41 GMT+0200 (EET) Server is listening on port 8881
/Users/gabi/Downloads/livecodingtv-bot-master/Client.js:25
            console.log('CLIENT ERROR: ', err, err.stanza, err.stanza.Stanza);

TypeError: Cannot read property 'Stanza' of undefined
    at Client.<anonymous> (/Users/gabi/Downloads/livecodingtv-bot-master/Client.js:25:61)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at /Users/gabi/Downloads/livecodingtv-bot-master/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/SRV.js:162:22
    at cb1 (/Users/gabi/Downloads/livecodingtv-bot-master/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/SRV.js:93:5)
    at GetAddrInfoReqWrap.asyncCallback [as callback](dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:77:17)

**Comment by blackburn1911** [comment]
``Sun Oct 25 2015 15:59:41 GMT+0200 (EET) Server is listening on port 8881
/Users/gabi/Downloads/livecodingtv-bot-master/Client.js:25
			console.log('CLIENT ERROR: ', err, err.stanza, err.stanza.Stanza);

TypeError: Cannot read property 'Stanza' of undefined
    at Client.<anonymous> (/Users/gabi/Downloads/livecodingtv-bot-master/Client.js:25:61)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at /Users/gabi/Downloads/livecodingtv-bot-master/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/SRV.js:162:22
    at cb1 (/Users/gabi/Downloads/livecodingtv-bot-master/node_modules/node-xmpp/node_modules/node-xmpp-core/lib/SRV.js:93:5)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:17)``

**Comment by R4ver** [comment]
Have you run `npm install` before you started the bot?

**Comment by marianvlad** [comment]
Sure

**Comment by tankerkiller125** [comment]
Also get the same error. This only happens when the credentials are wrong.

**Comment by marianvlad** [comment]
@tankerkiller125 Yep, that is the problem. Thanks

**Comment by owenconti** [comment]
This should be fixed with the next push.
